Update adapter to follow prebid conventions
glimpse-protocol/Prebid.js pull request #1
Opened 2021-11-18 12:22 UTC by samueldobbie

2021-12-01 19:49 UTC, tim-hm requested changes
Can you squash the fixup commit and I'd like to ask a few questions about the changes as I'm struggling to keep up with ya!

Otherwise code looks good.l

2021-12-01 19:49 UTC, tim-hm commented on modules/glimpseBidAdapter.js
> +const ENDPOINT = 'https://api.glimpsevault.local/ads/serving/public/v1/prebid'
Did you mean to commit with this pointing at local?

2021-12-01 20:12 UTC, tim-hm commented
One other comment .. for the commit message / body, you could add more about the why of these changes (and provide a link to the git issue discussion on the prebid repo). Just helpful to have that context when reviewing (unless i'm lost here!)

2021-12-02 15:46 UTC, tim-hm approved these changes
Did you mean to modify and commit `package-lock.json`?

2021-12-02 17:38 UTC, samueldobbie commented
@tim-hm Elaborated on the changes within the commit message & removed the empty line causing the `package-lock.json` change.

2021-12-08 18:57 UTC, merged