Glimpse/feature/optimize request body
glimpse-protocol/Prebid.js pull request #12
Opened 2022-03-11 16:52 UTC by eddieyu1998

## Type of change

- [x] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- Pass gvlid to storage manager for the gdpr use cases
- Update Glimpse prebid endpoint
- Include consent info in query params for better efficiency and privacy of the handling pf the data
- Update the request post body shape to optimize the size of the request
- Refactor and rename some util functions
- Reformat the entire file

close https://github.com/glimpse-protocol/prebid/issues/1 https://github.com/glimpse-protocol/prebid/issues/2 https://github.com/glimpse-protocol/prebid/issues/3

2022-03-15 11:35 UTC, tim-hm requested changes
Code looks clean 🙏 Before I start tinkering, can you make a few changes please?

 - squash into 1 commit (don't think origin will want it as separate commits)
 - rebase on origin/HEAD
 - double check the PR checks ... pretty sure there is an api change?
 - we'll need to submit a corresponding docs update as well
 - can you create 3 demo pages corresponding to our adaptors:
   - pbjs next (this one and we can replace next with the version number we're likely to get into)
   - pbjs 660 (previous release)
   - pbjs 5.17 (whats currently live on most of immeidate's sites

2022-03-18 17:14 UTC, eddieyu1998 commented
related docs pr
https://github.com/glimpse-protocol/prebid.github.io/pull/5

2022-03-18 17:35 UTC, eddieyu1998 commented
@tim-hm All done!

2022-03-18 17:36 UTC, eddieyu1998 commented
well except the demo pages

2022-03-22 10:54 UTC, tim-hm requested changes
This is excellent. A few bits to address and then I'll want to test the result with the new controller backend before submitting it.

1. I've compared the spec's definition with bidderFactor.js jsdoc parameters in and cannot spot why the linter is complaining. I've tried adding `aliases:[]` but it still complains. Do you know what the issue is?

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/1335525/159463698-c80f1425-081b-4bc2-9795-d6e1ac93d507.png">

2. There's a trailing `&` in the query params ... not a huge issue as I think its their function that does the appending and always add a trailing `&`.

Here's how triple lift deal with it:
```js
if (tlCall.lastIndexOf('&') === tlCall.length - 1) {
      tlCall = tlCall.substring(0, tlCall.length - 1);
    }
```

<img width="709" alt="image" src="https://user-images.githubusercontent.com/1335525/159463886-35eb849e-a8de-4872-9e2b-2f14c830c87d.png">

4. I think we should remove `bidderCode` until if/when we actually need it

5. `setDataInLocalStorage` and `getDataFromLocalStorage` both accept cbs. I can't see any reason to use them, can you?

6. I've given two examples inline of reducing some of the helper functions to make them simpler. I think we can remove a lot of the helper functions in perference for the null-call operator. Two examples inline for `getReferer` and `isGdprApplies`

7. I think we should update `getFirstPartyData()` to be less perscriptive and remove blank values from the request. For example:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/1335525/159468671-d4fb347a-ccee-4490-8652-2793e8f9d681.png">

Should be reduced to:

```js
fpd: {
  user: {
    attributes: {
      permutive: {
      keywords: ["apples"] 
      }
   } 
  }
}
```

Additionally, I think we should just take `site` and `user` directly from the pubs config. For example:

```js
 const fdp = { site: getConfig("ortb2.site"), user: getConfig("ortb2.site") }.

From what I can tell in the [fpd docs](https://docs.prebid.org/dev-docs/modules/validationFpdModule.html) site will have the keywords property on it if its available and so we don't need to do anything addition?
```

2022-03-22 10:54 UTC, tim-hm commented on modules/glimpseBidAdapter.js
> +      hasValue(bid) && hasValue(bid.params) && isString(bid.params.placementId)
In the first line of the comment above how about the simpler "Determines if the bid request is valid"

2022-03-22 10:54 UTC, tim-hm commented on modules/glimpseBidAdapter.js
>    /**
How about the simpler "Builds the http request"

2022-03-22 10:54 UTC, tim-hm commented on modules/glimpseBidAdapter.js
>    /**
How about "Parse http response"

2022-03-22 10:54 UTC, tim-hm commented on modules/glimpseBidAdapter.js
>    interpretResponse: (bidResponse) => {
mabybe `bidResponse` -> `response` since the "bid response" is actually on the data object

2022-03-22 10:54 UTC, tim-hm commented on modules/glimpseBidAdapter.js
>  function getReferer(bidderRequest) {
Does this seem a excessive? Ie whats wrong with:

```
function getReferer(bidderRequest) {
  return bidderRequest?.refererInfo?.referer ?? ""
}
```

2022-03-22 10:54 UTC, tim-hm commented on modules/glimpseBidAdapter.js
> +}
Does this reduce to:

```js
function isGdprApplies(bidderRequest) {
  return Boolean(bidderRequest?.gdprConsent?.gdprApplies)
}
```

2022-03-22 10:54 UTC, tim-hm commented on modules/glimpseBidAdapter.js
> +function isGdprApplies(bidderRequest) {
Maybe rename to `doesGdprApply` or just `gdprApplies()`

2022-03-25 10:15 UTC, eddieyu1998 commented on modules/glimpseBidAdapter.js
> +      hasValue(bid) && hasValue(bid.params) && isString(bid.params.placementId)
yes much concise

2022-03-25 10:15 UTC, eddieyu1998 commented on modules/glimpseBidAdapter.js
>    /**
cool

2022-03-25 10:17 UTC, eddieyu1998 commented on modules/glimpseBidAdapter.js
>    /**
sure

2022-03-25 10:35 UTC, eddieyu1998 commented on modules/glimpseBidAdapter.js
>  function getReferer(bidderRequest) {
agree

2022-03-25 10:35 UTC, eddieyu1998 commented on modules/glimpseBidAdapter.js
> +function isGdprApplies(bidderRequest) {
renamed!

2022-03-25 11:06 UTC, eddieyu1998 commented on modules/glimpseBidAdapter.js
> +}
yes

2022-03-25 11:37 UTC, eddieyu1998 commented
if we use this fpd setup, then the resulting fpd object would look like this. Do we want to use this final shape, or remove the ext.data layer and keep using the original shape?

```
const fdp = { site: getConfig("ortb2.site"), user: getConfig("ortb2.site") }
```

![image](https://user-images.githubusercontent.com/32135564/160113795-19c89222-db46-43bb-9527-4350652d1342.png)

2022-03-25 11:46 UTC, eddieyu1998 commented
i.e.
original fpd shape
```
fpd: {
  site: {
    keywords: ["site", "keywords"],
    attributes: {
      permutive: {
        keywords: ["site", "keywords"],
        pvc: {}
      }
    }
  },
  user: {
    keywords: ["user", "keywords"],
    attributes: {
      permutive: {
        keywords" ["permutive", "segments"],
        enrichers: {}
      }
    }
  }
}
```

new shape using `const fdp = { site: getConfig("ortb2.site"), user: getConfig("ortb2.site") }` without any modification

```
{
  "site": {
    "keywords": "site,keywords",
    "ext": {
      "data": {
        "permutive": {
          "keywords": ["custom", "site", "keywords"],
          "pvc": {}
        }
      }
    }
  },
  "user": {
    "keywords": "user,keywords",
    "ext": {
      "data": {
        "permutive": {
          "keywords": ["apples"],
          "enrichers": {}
        }
      }
    }
  }
}

```

2022-03-25 13:13 UTC, tim-hm commented
I think we want to stay aligned with the default shape (so the 2nd option).

One thought occurs to me, why not just use `cosnt fpd = getConfig("ortb2")` for simplicity?

2022-03-25 20:03 UTC, eddieyu1998 commented
all done now, also refactored most of the functions and removed lots of unnecessary stuff. I think it's in quite a clean state now.

2022-03-25 20:10 UTC, eddieyu1998 commented
If you plan on reviewing the PRs during weekend I'll try to also update the docs PR tmr and hopefully submit the PRs to the Prebid repos.

2022-03-29 19:21 UTC, tim-hm approved these changes
Great work eddie 🙏

2022-03-30 10:03 UTC, merged